# Generated by Django 3.2.8 on 2021-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnalawyer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_rating',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
